### ISSUE TITLE
Roadmap to Sotopia v0.1 

### ISSUE THREAD

**Issue by ProKil** [sotopia-lab/sotopia#70]
### Description

Issues that we want to address before releasing v0.1. 

Generally, we would like to have:

1. https://docs.sotopia.world which contains the explanation of the basic concepts of sotopia and how to use them. 
2. Colab tutorial series which allows users to start using sotopia in just a couple of minutes. 
3. Benchmarking API
4. Less dependencies. Remove the ones we don't use (v0.1), and cut the ones we don't actually rely on (for v0.2). 

#### A website to host sotopia docs
- [x] #75 @ProKil 
- [x] #76 @ProKil 
- [x] Update installation instruction and tutorial with #122 
- [x] CLI docs @XuhuiZhou 
- [x] Create new characters and scenarios
- [x] #77
- [x] ~~#85~~ Pushed to v0.2

#### Installation
- [x] #122 @ProKil 

#### Tutorial Series
- [x] 1.1 Play with Sotopia in Colab by @ProKil 
- [x] #71 by @ProKil 

#### Benchmarking 
- [x] #68 by @XuhuiZhou 
- [x] #69 @XuhuiZhou 
- [x] #135 @bugsz @XuhuiZhou 

#### Cut dependencies
- [x] #59 @ProKil 
- [x] #82 @ProKil

**Comment by lwaekfjlk** [comment]
I think it indeed takes a lot of work but I believe it can be worth writing to support `sotopia-lite` that does not rely on any external database and directly save files into jsonlines or csv.

**Comment by XuhuiZhou** [comment]
> One potential wish: I think it indeed takes a lot of work but I believe it can be worth writing to support `sotopia-lite` that does not rely on any external database and directly save files into jsonlines or csv

I in general like the idea (redis is powerful yet in many cases it might overkill)

**Comment by lwaekfjlk** [comment]
> > One potential wish: I think it indeed takes a lot of work but I believe it can be worth writing to support `sotopia-lite` that does not rely on any external database and directly save files into jsonlines or csv
> 
> I in general like the idea (redis is powerful yet in many cases it might overkill)

Yes, one potential problems is when working on a docker-based server. It can be hard to host another redis on that.

**Comment by lwaekfjlk** [comment]
> > Yes, one potential problem is when working on a docker-based server. It can be hard to host another redis on that.
> 
> Have you tried the method in the google colab? It doesn't require docker. Let me know if it doesn't work.

good point. No I haven't. I will try that. Thanks for pointing this out.

**Comment by ProKil** [comment]
@lwaekfjlk I have added the instruction to the current http://docs.sotopia.world. Please check that out.

**Comment by lwaekfjlk** [comment]
yes, I saw that. Super interesting and fun.
